# Generated by Django 5.2.7 on 2025-11-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrecruitai', '0005_candidate_gitlab_url_candidate_portfolio_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='required_soft_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
